# Grafana Datasource Configuration for Victoria Metrics
apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoria:8428
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s
